FROM node:6

# update npm
RUN npm install npm@5.6.0
RUN rm -rf /usr/local/lib/node_modules/npm
RUN mv node_modules/npm /usr/local/lib/node_modules/npm

ENV NODE_ENV production
COPY ../portal /home/node/app
WORKDIR /home/node/app

COPY ../translations/walsin ./app/translations

COPY ../urls/walsin/urls.conf.js ./

COPY ../logo/walsin/logoCompany.png ./app/containers/LoginPage/

RUN npm install

RUN npm run build

# port 3000 for portal
EXPOSE 3000

CMD npm run start:prod
