FROM node:6

# update npm
RUN npm install npm@5.6.0
RUN rm -rf /usr/local/lib/node_modules/npm
RUN mv node_modules/npm /usr/local/lib/node_modules/npm

ENV NODE_ENV development
COPY ./portal /home/node/app
WORKDIR /home/node/app

COPY ./translations/default ./app/translations

COPY ./urls/default/urls.conf.js ./

COPY ./logo/default/logoCompany.png ./app/containers/LoginPage/

RUN npm install

RUN npm run build

# port 3000 for portal
EXPOSE 3000

CMD npm run start:prod
