export const colorArr = [
  {
    backgroundColor: '#9E9E9E',
    borderColor: '#EEEEEE',
    hoverBackgroundColor: '#BDBDBD',
    hoverBorderColor: '#EEEEEE',
    color: '#EEEEEE',
  },
  {
    backgroundColor: '#1976D2',
    borderColor: '#7986CB',
    hoverBackgroundColor: '#90CAF9',
    hoverBorderColor: '#7986CB',
    color: '#7986CB',
  },
  {
    backgroundColor: '#EF5350',
    borderColor: '#FFCDD2',
    hoverBackgroundColor: '#E57373',
    hoverBorderColor: '#FFCDD2',
    color: '#FFCDD2',
  },
  {
    backgroundColor: '#EF5350',
    borderColor: '#FFCDD2',
    hoverBackgroundColor: '#E57373',
    hoverBorderColor: '#FFCDD2',
    color: '#FFCDD2',
  },
  {
    backgroundColor: '#EF5350',
    borderColor: '#FFCDD2',
    hoverBackgroundColor: '#E57373',
    hoverBorderColor: '#FFCDD2',
    color: '#FFCDD2',
  },
  {
    backgroundColor: '#EF5350',
    borderColor: '#FFCDD2',
    hoverBackgroundColor: '#E57373',
    hoverBorderColor: '#FFCDD2',
    color: '#FFCDD2',
  },
  {
    backgroundColor: '#EF5350',
    borderColor: '#FFCDD2',
    hoverBackgroundColor: '#E57373',
    hoverBorderColor: '#FFCDD2',
    color: '#FFCDD2',
  },
  {
    backgroundColor: '#EF5350',
    borderColor: '#FFCDD2',
    hoverBackgroundColor: '#E57373',
    hoverBorderColor: '#FFCDD2',
    color: '#FFCDD2',
  },
];
